const express = require('express');
const router = express.Router();
const { getAllResources, addResource, updateResource, deleteResource } = require('../controllers/adminController');
const verifyToken = require('../middleware/auth');
const adminOnly = require('../middleware/adminOnly');
router.use(verifyToken, adminOnly);
router.get('/resources', getAllResources);
router.post('/resources', addResource);
router.put('/resources/:id', updateResource);
router.delete('/resources/:id', deleteResource);
module.exports = router;